### ISSUE TITLE
NameError: name 'moving_avg_meter' is not defined

### ISSUE THREAD

**Issue by duzhenjiang113** [liruihui/SP-GAN#1]
It seems that there are some issues with the code of model.py. Could you please help me to solve them?
Thanks!

**Comment by liruihui** [comment]
Delete the redundant variable.
The sphere S is defined here.

https://github.com/liruihui/SP-GAN/blob/main/Generation/model.py#L156:9

**Comment by duzhenjiang113** [comment]
> Delete the redundant variable.
> The sphere S is defined here.
> 
> https://github.com/liruihui/SP-GAN/blob/main/Generation/model.py#L156:9

Thanks for your reply.

----- np.loadtxt('template/balls/%d.xyz'%self.opts.np)

Could you please tell me how to get the file of *.xyz. Would there be any harm in using Gaussian distribution instead of sphere S?

**Comment by liruihui** [comment]
The global Prior is shared. That is the key.
Actually, there is no constrain on S, it can be cube or others.

**Comment by duzhenjiang113** [comment]
> The global Prior is shared. That is the key.
> Actually, there is no constrain on S, it can be cube or others.

okay
