### ISSUE TITLE
chamferdistcuda

### ISSUE THREAD

**Issue by ImaneChafi** [liruihui/SP-GAN#10]
Hi, thank you for the great code! I have some issues with the train.py file. This error appears on personal training data set once the h5 files have been created and read:

`ImportError: cannot import name 'chamferdistcuda' from 'metrics.CD_EMD.cd' (unknown location) `

in file `SP-GAN-main\metrics\CD_EMD\cd\chamferdist\ChamferDistance.py`

Thank you for your time!

**Comment by hjoh01** [comment]
Hi, have you figured it out already?
I encountered the same issue as yours, and below is how I fixed the problem.
in file ```\metrics\CD_EMD\cd\chamferdist\ChamferDistance.py```,
I changed line 7, ```from CD_EMD.cd import chamferdistcuda as chamfer``` into ```from CD_EMD.cd.chamferdist import ChamferDistance as chamfer``` and fixed it.

**Comment by ImaneChafi** [comment]
Hi! 

Sorry for the delay, yes I've fixed it!! Thank you so much for your help!
